In [1]:
# ============================================================
# IMPORTS
# ============================================================

import yaml
import joblib
import numpy as np
import pandas as pd

from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    precision_score,
    recall_score,
    f1_score,
    accuracy_score
)

In [3]:
# ============================================================
# LOAD DATA
# ============================================================

TARGET = "SeriousDlqin2yrs"

df = pd.read_csv(
    "../data/processed/final_modeling_dataset_v1.csv"
)

X = df.drop(columns=TARGET)
y = df[TARGET]

In [4]:
# ============================================================
# TRAIN TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,

    test_size=0.20,

    stratify=y,

    random_state=42

)

In [7]:
# ============================================================
# LOAD PARAMETERS
# ============================================================

with open(
    "../config/params_all.yaml",
    "r"
) as f:

    params = yaml.safe_load(f)

In [8]:
# ============================================================
# SCALE POS WEIGHT
# ============================================================

scale_pos_weight = (

    (y_train == 0).sum()

    /

    (y_train == 1).sum()

)

In [9]:
# ============================================================
# FINAL CATBOOST
# ============================================================

cat_params = params["models"]["catboost"]["params"]

cat_fixed = params["models"]["catboost"]["fixed_params"]

cat_model = CatBoostClassifier(

    **cat_params,

    **cat_fixed

)

cat_model.fit(

    X_train,
    y_train

)

CatBoostClassifier(auto_class_weights='Balanced', bagging_temperature=4.981705771557597, depth=4, eval_metric='AUC', iterations=690, l2_leaf_reg=1.531587794641683, learning_rate=0.033840528471303886, loss_function='Logloss', random_seed=42, random_strength=4.891319693380929, verbose=False)

In [10]:
# ============================================================
# FINAL XGBOOST
# ============================================================

xgb_params = params["models"]["xgboost"]["params"]

xgb_fixed = params["models"]["xgboost"]["fixed_params"]

xgb_fixed["scale_pos_weight"] = scale_pos_weight

xgb_model = XGBClassifier(

    **xgb_params,

    **xgb_fixed

)

xgb_model.fit(

    X_train,
    y_train

)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.7872279670202367, device=None,
              early_stopping_rounds=None, enable_categorical=True,
              eval_metric='logloss', feature_types=None, feature_weights=None,
              gamma=4.227205255766471, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.026779927855344533,
              max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=7, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=405, n_jobs=-1,
              num_parallel_tree=None, ...)

In [11]:
# ============================================================
# FINAL LIGHTGBM
# ============================================================

lgb_params = params["models"]["lightgbm"]["params"]

lgb_fixed = params["models"]["lightgbm"]["fixed_params"]

lgb_model = LGBMClassifier(

    **lgb_params,

    **lgb_fixed

)

lgb_model.fit(

    X_train,
    y_train

)

LGBMClassifier(class_weight='balanced', colsample_bytree=0.6778295850299293,
               learning_rate=0.022982417290086602, max_depth=7, metric='auc',
               min_child_samples=40, n_estimators=377, n_jobs=-1, num_leaves=21,
               objective='binary', random_state=42,
               reg_alpha=9.98475745038443e-06, reg_lambda=0.015911771617773646,
               subsample=0.6376273342959565, verbosity=-1)

In [12]:
# ============================================================
# PROBABILITIES
# ============================================================

cat_probs = cat_model.predict_proba(
    X_test
)[:,1]

xgb_probs = xgb_model.predict_proba(
    X_test
)[:,1]

lgb_probs = lgb_model.predict_proba(
    X_test
)[:,1]

In [19]:
# ============================================================
# THRESHOLD OPTIMIZATION
# ============================================================

def optimize_threshold(

    y_true,

    probs,

    recall_target=0.75

):

    rows=[]

    for threshold in np.arange(

        0.01,
        1.00,
        0.01

    ):

        preds = (

            probs >= threshold

        ).astype(int)

        precision = precision_score(
            y_true,
            preds,
            zero_division=0
        )

        recall = recall_score(
            y_true,
            preds
        )

        f1 = f1_score(
            y_true,
            preds
        )

        rows.append({

            "Threshold":threshold,

            "Precision":precision,

            "Recall":recall,

            "F1":f1

        })

    df = pd.DataFrame(rows)

    df = df[
        df["Recall"] >= recall_target
    ]

    return df.sort_values(

        "F1",

        ascending=False

    ).reset_index(drop=True)

In [20]:
# ============================================================
# RUN THRESHOLD SEARCH
# ============================================================

cat_thresholds = optimize_threshold(

    y_test,

    cat_probs

)

xgb_thresholds = optimize_threshold(

    y_test,

    xgb_probs

)

lgb_thresholds = optimize_threshold(

    y_test,

    lgb_probs

)

In [21]:
# ============================================================
# BEST THRESHOLDS
# ============================================================

display(cat_thresholds.head())

display(xgb_thresholds.head())

display(lgb_thresholds.head())

   Threshold  Precision    Recall        F1
0       0.54   0.238606  0.754613  0.362569
1       0.53   0.233069  0.762095  0.356968
2       0.52   0.228791  0.772070  0.352981
3       0.51   0.222922  0.777057  0.346453
4       0.50   0.218338  0.785037  0.341654

   Threshold  Precision    Recall        F1
0       0.54   0.237232  0.750623  0.360522
1       0.53   0.231622  0.760599  0.355105
2       0.52   0.226651  0.768579  0.350068
3       0.51   0.222555  0.778554  0.346158
4       0.50   0.217409  0.783541  0.340375

   Threshold  Precision    Recall        F1
0       0.53   0.232351  0.755112  0.355357
1       0.52   0.228597  0.763092  0.351805
2       0.51   0.223736  0.770075  0.346733
3       0.50   0.219378  0.778055  0.342255
4       0.49   0.214627  0.783042  0.336910

# Ensamble Experiments

In [22]:
# ============================================================
# ENSEMBLE PROBABILITIES
# ============================================================

ensemble_probs = {

    "Equal Voting":
        (
            cat_probs +
            xgb_probs +
            lgb_probs
        ) / 3,

    "Weighted 50-25-25":
        (
            0.50 * cat_probs +
            0.25 * xgb_probs +
            0.25 * lgb_probs
        ),

    "Weighted 40-30-30":
        (
            0.40 * cat_probs +
            0.30 * xgb_probs +
            0.30 * lgb_probs
        ),

    "CatBoost + XGBoost":
        (
            cat_probs +
            xgb_probs
        ) / 2,

    "CatBoost + LightGBM":
        (
            cat_probs +
            lgb_probs
        ) / 2,

    "XGBoost + LightGBM":
        (
            xgb_probs +
            lgb_probs
        ) / 2

}

In [23]:
# ============================================================
# THRESHOLD OPTIMIZATION
# ============================================================

ensemble_results = {}

for name, probs in ensemble_probs.items():

    print("=" * 80)
    print(name)
    print("=" * 80)

    result = optimize_threshold(
        y_test,
        probs,
        recall_target=0.75
    )

    ensemble_results[name] = result

    display(
        result.head()
    )

================================================================================
Equal Voting
================================================================================

   Threshold  Precision    Recall        F1
0       0.54   0.238208  0.750623  0.361648
1       0.53   0.232747  0.758603  0.356206
2       0.52   0.227777  0.768080  0.351358
3       0.51   0.223775  0.774564  0.347233
4       0.50   0.219356  0.784539  0.342851

================================================================================
Weighted 50-25-25
================================================================================

   Threshold  Precision    Recall        F1
0       0.54   0.238615  0.752618  0.362348
1       0.53   0.233609  0.760599  0.357436
2       0.52   0.228216  0.768080  0.351879
3       0.51   0.223465  0.777057  0.347109
4       0.50   0.219277  0.784040  0.342708

================================================================================
Weighted 40-30-30
================================================================================

   Threshold  Precision    Recall        F1
0       0.54   0.238419  0.752120  0.362065
1       0.53   0.232961  0.758603  0.356457
2       0.52   0.228047  0.768080  0.351678
3       0.51   0.223627  0.776060  0.347205
4       0.50   0.219155  0.784040  0.342558

================================================================================
CatBoost + XGBoost
================================================================================

   Threshold  Precision    Recall        F1
0       0.54   0.237480  0.752120  0.360981
1       0.53   0.233603  0.762095  0.357594
2       0.52   0.227990  0.771072  0.351924
3       0.51   0.223398  0.779052  0.347227
4       0.50   0.218668  0.787531  0.342294

================================================================================
CatBoost + LightGBM
================================================================================

   Threshold  Precision    Recall        F1
0       0.54   0.239068  0.752618  0.362871
1       0.53   0.233778  0.760100  0.357579
2       0.52   0.228674  0.766085  0.352213
3       0.51   0.223374  0.774065  0.346699
4       0.50   0.218868  0.781047  0.341921

================================================================================
XGBoost + LightGBM
================================================================================

   Threshold  Precision    Recall        F1
0       0.53   0.232252  0.757107  0.355462
1       0.52   0.227414  0.764589  0.350560
2       0.51   0.223279  0.773067  0.346485
3       0.50   0.218492  0.779052  0.341272
4       0.49   0.214228  0.788529  0.336921

In [24]:
# ============================================================
# FINAL ENSEMBLE EVALUATION
# ============================================================

from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    average_precision_score,
    precision_score,
    recall_score,
    f1_score
)

comparison = []

for name, probs in ensemble_probs.items():

    best = ensemble_results[name].iloc[0]

    threshold = best["Threshold"]

    preds = (
        probs >= threshold
    ).astype(int)

    comparison.append({

        "Model": name,

        "Threshold": threshold,

        "Accuracy":
            accuracy_score(
                y_test,
                preds
            ),

        "ROC-AUC":
            roc_auc_score(
                y_test,
                probs
            ),

        "PR-AUC":
            average_precision_score(
                y_test,
                probs
            ),

        "Precision":
            precision_score(
                y_test,
                preds
            ),

        "Recall":
            recall_score(
                y_test,
                preds
            ),

        "F1":
            f1_score(
                y_test,
                preds
            )

    })

comparison_df = (
    pd.DataFrame(comparison)
    .sort_values(
        by="F1",
        ascending=False
    )
    .reset_index(drop=True)
)

display(comparison_df)

,Model,Threshold,Accuracy,ROC-AUC,PR-AUC,Precision,Recall,F1
0,CatBoost + LightGBM,0.54,0.823367,0.870994,0.403109,0.239068,0.752618,0.362871
1,Weighted 50-25-25,0.54,0.822967,0.870943,0.403277,0.238615,0.752618,0.362348
2,Weighted 40-30-30,0.54,0.822867,0.870873,0.403351,0.238419,0.752120,0.362065
3,Equal Voting,0.54,0.822900,0.870804,0.403104,0.238208,0.750623,0.361648
4,CatBoost + XGBoost,0.54,0.822033,0.870768,0.403292,0.237480,0.752120,0.360981
5,XGBoost + LightGBM,0.53,0.816500,0.870305,0.401782,0.232252,0.757107,0.355462

In [25]:
# ============================================================
# FINAL ENSEMBLE EVALUATION
# ============================================================

from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    average_precision_score,
    precision_score,
    recall_score,
    f1_score
)

comparison = []

for name, probs in ensemble_probs.items():

    best = ensemble_results[name].iloc[0]

    threshold = best["Threshold"]

    preds = (
        probs >= threshold
    ).astype(int)

    comparison.append({

        "Model": name,

        "Threshold": threshold,

        "Accuracy":
            accuracy_score(
                y_test,
                preds
            ),

        "ROC-AUC":
            roc_auc_score(
                y_test,
                probs
            ),

        "PR-AUC":
            average_precision_score(
                y_test,
                probs
            ),

        "Precision":
            precision_score(
                y_test,
                preds
            ),

        "Recall":
            recall_score(
                y_test,
                preds
            ),

        "F1":
            f1_score(
                y_test,
                preds
            )

    })

comparison_df = (
    pd.DataFrame(comparison)
    .sort_values(
        by="F1",
        ascending=False
    )
    .reset_index(drop=True)
)

display(comparison_df)

,Model,Threshold,Accuracy,ROC-AUC,PR-AUC,Precision,Recall,F1
0,CatBoost + LightGBM,0.54,0.823367,0.870994,0.403109,0.239068,0.752618,0.362871
1,Weighted 50-25-25,0.54,0.822967,0.870943,0.403277,0.238615,0.752618,0.362348
2,Weighted 40-30-30,0.54,0.822867,0.870873,0.403351,0.238419,0.752120,0.362065
3,Equal Voting,0.54,0.822900,0.870804,0.403104,0.238208,0.750623,0.361648
4,CatBoost + XGBoost,0.54,0.822033,0.870768,0.403292,0.237480,0.752120,0.360981
5,XGBoost + LightGBM,0.53,0.816500,0.870305,0.401782,0.232252,0.757107,0.355462